//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTicket.API2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUser
    {
        public int EventID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        
        public virtual Event Event { get; set; }
        public virtual EventUserRole EventUserRole { get; set; }
        public virtual User User { get; set; }
    }
}
